version: '3'
services:
  dev:
    build:
      context: .
    ports:
      - 3000:3000
    command: yarn start
    volumes:
      - "./src:/factsCats/src"
  test:
    build:
      context: .
    environment:
      - CI=true
    command: yarn test